tap "homebrew/core"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/bundle"
tap "heroku/brew"

brew "mas" # mac app store

cask "alfred"
cask "android-file-transfer"
cask "appcleaner"
cask "bettertouchtool"
cask "disk-inventory-x"
cask "dropbox"
cask "firefox"
cask "focusrite-control"
cask "handbrake"
cask "idrive"
# cask "logitech-g-hub"
cask "logitech-options"
cask "nordvpn"
cask "notion"
# cask "scroll-reverser" # replaced by a BTT setting
# cask "skyfonts"
cask "spotify"
# cask "steelseries-engine"
cask "the-unarchiver"
cask "vlc"
cask "zoom"

mas "Amphetamine", id: 937984704
# mas "Bear", id: 1091189122
mas "Color Blind Pal", id: 1023111433
mas "GIPHY CAPTURE", id: 668208984
mas "Speedtest by Ookla", id: 1153157709
# mas "Trello", id: 1278508951
